// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQOKJwCnBTKAQjIbkSb45PM5cPuvdutI',
    appId: '1:444245300519:web:6101c2cf01a5577473c502',
    messagingSenderId: '444245300519',
    projectId: 'al-kodir-shop',
    authDomain: 'al-kodir-shop.firebaseapp.com',
    storageBucket: 'al-kodir-shop.appspot.com',
    measurementId: 'G-7R6LXV1TSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFYt1l-0sCl9t2UQf8Fz1vR5Y0WeSaDcE',
    appId: '1:444245300519:android:b1a556529e60c45273c502',
    messagingSenderId: '444245300519',
    projectId: 'al-kodir-shop',
    storageBucket: 'al-kodir-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDss_zFThkF23abXBfdWxK8Ie6bi53zsu0',
    appId: '1:444245300519:ios:ff04c40aca7c2b6473c502',
    messagingSenderId: '444245300519',
    projectId: 'al-kodir-shop',
    storageBucket: 'al-kodir-shop.appspot.com',
    iosBundleId: 'com.example.shopiKg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDss_zFThkF23abXBfdWxK8Ie6bi53zsu0',
    appId: '1:444245300519:ios:0dc7d5ffdf04cc0173c502',
    messagingSenderId: '444245300519',
    projectId: 'al-kodir-shop',
    storageBucket: 'al-kodir-shop.appspot.com',
    iosBundleId: 'com.example.shopiKg.RunnerTests',
  );
}
